### ISSUE TITLE
Audit Summary Checklist

### ISSUE THREAD

**Issue by chanharryhk** [dfx-finance/protocol-v2#67]
- [x] Issue #36 (Oracle Front Run):
PR: Will set up AMM infra post audit see discussion [here](https://github.com/dfx-finance/protocol-v2/issues/36#issuecomment-1254385897) new issue [here](https://github.com/dfx-finance/protocol-v2/issues/56#issuecomment-1255359398)

- [x] Issue #37 (Missing Proxy Protection)
PR [here](https://github.com/dfx-finance/protocol-v2/pull/61)

- [x] Issue #38 (DepositWithWhitelist Validation)
PR [here](https://github.com/dfx-finance/protocol-v2/pull/66)

- [x] Issue #39 (Unclear Error)
PR [here](https://github.com/dfx-finance/protocol-v2/pull/65)

- [x] Issue #40 (Emergency State Clarification)
PR [here](https://github.com/dfx-finance/protocol-v2/pull/64)

- [x] Issue #41 (Transactable Check)
PR: Is intentional see discussion [here](https://github.com/dfx-finance/protocol-v2/issues/41#issuecomment-1258224943)

- [x] Issue #42 (Protected Function)
PR [here](https://github.com/dfx-finance/protocol-v2/pull/68)

- [x] Issue #43 (Verification)
PR [here](https://github.com/dfx-finance/protocol-v2/pull/55)

- [x] Issue #44 (newAssimilator Definition)
PR [here](https://github.com/dfx-finance/protocol-v2/pull/54)

- [x] Issue #45 (Overwriting Curve)
PR [here](https://github.com/dfx-finance/protocol-v2/pull/63)

- [x] Issue #46  (Potential Time Lag)
PR [here](https://github.com/dfx-finance/protocol-v2/pull/53)

- [x] Issue #47  (Unnecessary Function)
PR [here](https://github.com/dfx-finance/protocol-v2/pull/52)

- [x] Issue #48  (Library Update)
PR [here](https://github.com/dfx-finance/protocol-v2/pull/62)

- [x] Issue #49  (Currency Check)
PR [here](https://github.com/dfx-finance/protocol-v2/pull/58)

- [x] Issue #50  (Equivalent Function)
PR [here](https://github.com/dfx-finance/protocol-v2/pull/59)
